package com.dafeng.mymodibleassistant.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.dafeng.mymodibleassistant.dao.TbApp;
import com.dafeng.mymodibleassistant.dao.TbJump;
import com.dafeng.mymodibleassistant.dao.TbShortcut;

import com.dafeng.mymodibleassistant.dao.TbAppDao;
import com.dafeng.mymodibleassistant.dao.TbJumpDao;
import com.dafeng.mymodibleassistant.dao.TbShortcutDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig tbAppDaoConfig;
    private final DaoConfig tbJumpDaoConfig;
    private final DaoConfig tbShortcutDaoConfig;

    private final TbAppDao tbAppDao;
    private final TbJumpDao tbJumpDao;
    private final TbShortcutDao tbShortcutDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        tbAppDaoConfig = daoConfigMap.get(TbAppDao.class).clone();
        tbAppDaoConfig.initIdentityScope(type);

        tbJumpDaoConfig = daoConfigMap.get(TbJumpDao.class).clone();
        tbJumpDaoConfig.initIdentityScope(type);

        tbShortcutDaoConfig = daoConfigMap.get(TbShortcutDao.class).clone();
        tbShortcutDaoConfig.initIdentityScope(type);

        tbAppDao = new TbAppDao(tbAppDaoConfig, this);
        tbJumpDao = new TbJumpDao(tbJumpDaoConfig, this);
        tbShortcutDao = new TbShortcutDao(tbShortcutDaoConfig, this);

        registerDao(TbApp.class, tbAppDao);
        registerDao(TbJump.class, tbJumpDao);
        registerDao(TbShortcut.class, tbShortcutDao);
    }
    
    public void clear() {
        tbAppDaoConfig.getIdentityScope().clear();
        tbJumpDaoConfig.getIdentityScope().clear();
        tbShortcutDaoConfig.getIdentityScope().clear();
    }

    public TbAppDao getTbAppDao() {
        return tbAppDao;
    }

    public TbJumpDao getTbJumpDao() {
        return tbJumpDao;
    }

    public TbShortcutDao getTbShortcutDao() {
        return tbShortcutDao;
    }

}
