package com.dafeng.mymodibleassistant.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TB_APP".
 */
public class TbApp {

     private Long id;
     private String pkg;
     private String name;
     private Boolean isShow=true;
     private Boolean isPosIndependent=false;
     private Integer x=100;
     private Integer y=100;
     private Boolean isShowInputPicker=false;
     private String inputMethod;

    public TbApp() {
    }

    public TbApp(Long id) {
        this.id = id;
    }

    public TbApp(Long id, String pkg, String name, Boolean isShow, Boolean isPosIndependent, Integer x, Integer y, Boolean isShowInputPicker, String inputMethod) {
        this.id = id;
        this.pkg = pkg;
        this.name = name;
        this.isShow = isShow;
        this.isPosIndependent = isPosIndependent;
        this.x = x;
        this.y = y;
        this.isShowInputPicker = isShowInputPicker;
        this.inputMethod = inputMethod;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPkg() {
        return pkg;
    }

    public void setPkg(String pkg) {
        this.pkg = pkg;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Boolean getIsShow() {
        return isShow;
    }

    public void setIsShow(Boolean isShow) {
        this.isShow = isShow;
    }

    public Boolean getIsPosIndependent() {
        return isPosIndependent;
    }

    public void setIsPosIndependent(Boolean isPosIndependent) {
        this.isPosIndependent = isPosIndependent;
    }

    public Integer getX() {
        return x;
    }

    public void setX(Integer x) {
        this.x = x;
    }

    public Integer getY() {
        return y;
    }

    public void setY(Integer y) {
        this.y = y;
    }

    public Boolean getIsShowInputPicker() {
        return isShowInputPicker;
    }

    public void setIsShowInputPicker(Boolean isShowInputPicker) {
        this.isShowInputPicker = isShowInputPicker;
    }

    public String getInputMethod() {
        return inputMethod;
    }

    public void setInputMethod(String inputMethod) {
        this.inputMethod = inputMethod;
    }

}
