package com.dafeng.mymodibleassistant.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TB_JUMP".
 */
public class TbJump {

     private Long id;
     private Long appId;
     private Long jumpId;

    public TbJump() {
    }

    public TbJump(Long id) {
        this.id = id;
    }

    public TbJump(Long id, Long appId, Long jumpId) {
        this.id = id;
        this.appId = appId;
        this.jumpId = jumpId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getAppId() {
        return appId;
    }

    public void setAppId(Long appId) {
        this.appId = appId;
    }

    public Long getJumpId() {
        return jumpId;
    }

    public void setJumpId(Long jumpId) {
        this.jumpId = jumpId;
    }

}
