package com.dafeng.mymodibleassistant.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TB_SHORTCUT".
 */
public class TbShortcut {

     private Long id;
     private Long appId;

    public TbShortcut() {
    }

    public TbShortcut(Long id) {
        this.id = id;
    }

    public TbShortcut(Long id, Long appId) {
        this.id = id;
        this.appId = appId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getAppId() {
        return appId;
    }

    public void setAppId(Long appId) {
        this.appId = appId;
    }

}
